ARG PYTHON_VERSION=3.13
ARG BASE_RUNTIME_DISTRO=slim-bookworm
FROM python:${PYTHON_VERSION}-${BASE_RUNTIME_DISTRO}
LABEL org.opencontainers.image.authors="sinfallas@gmail.com"

ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"

RUN apt-get update -qq && apt-get -y dist-upgrade && apt-get -y install --no-install-recommends --no-install-suggests gnupg curl git build-essential zip unzip wget nano libffi-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjpeg-turbo-progs libjpeg62-turbo-dev liblcms2-dev libopenjp2-7-dev libtiff5-dev libwebp-dev libssl-dev freetds-dev freetds-bin unixodbc-dev tdsodbc && apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/lib/{dpkg,cache,log}
RUN curl -sSL https://install.python-poetry.org | python3 -
CMD ["/bin/bash"]
ARG BUILD_DATE
LABEL org.opencontainers.image.created=$BUILD_DATE
